ALTER TABLE tb_vistoria
    ADD COLUMN tipo_imovel VARCHAR(20);

CREATE TABLE tb_ambiente_vistoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vistoria_id BIGINT NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    nome VARCHAR(60) NOT NULL,
    ordem INTEGER NOT NULL,
    CONSTRAINT fk_ambiente_vistoria
        FOREIGN KEY (vistoria_id) REFERENCES tb_vistoria(id),
    CONSTRAINT uq_ambiente_vistoria_ordem
        UNIQUE (vistoria_id, ordem),
    CONSTRAINT uq_ambiente_vistoria_nome
        UNIQUE (vistoria_id, nome),
    CONSTRAINT ck_ambiente_vistoria_ordem
        CHECK (ordem >= 0 AND ordem < 30)
);

CREATE INDEX idx_ambiente_vistoria_vistoria
    ON tb_ambiente_vistoria(vistoria_id);

ALTER TABLE tb_imagem_vistoria
    ADD COLUMN ambiente_id BIGINT;

ALTER TABLE tb_imagem_vistoria
    ADD COLUMN categoria VARCHAR(20);

ALTER TABLE tb_imagem_vistoria
    ADD CONSTRAINT fk_imagem_ambiente
        FOREIGN KEY (ambiente_id) REFERENCES tb_ambiente_vistoria(id);

CREATE INDEX idx_imagem_vistoria_ambiente
    ON tb_imagem_vistoria(ambiente_id);
